<?php


return [

    'HELPDESK_API_URL' => env('HELPDESK_API_URL'),
    'HELPDESK_API_USERNAME' => env('HELPDESK_API_USERNAME'),
    'HELPDESK_API_PASSWORD' => env('HELPDESK_API_PASSWORD'),
    'HELPDESK_URL' => env('HELPDESK_URL'),
    'HELPDESK_TOKEN' => env('HELPDESK_TOKEN')
];